/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by AddOnGenerator 1.0.0 from webgme on Thu Oct 15 2015 13:25:43 GMT-0500 (CDT).
 */

define([
    'addOn/AddOnBase'
], function (AddOnBase) {
    'use strict';

    /**
     * Initializes a new instance of JSONLDExporter.
     * @class
     * @augments {AddOnBase}
     * @classdesc This class represents the addOn JSONLDExporter.
     * @constructor
     */
    var JSONLDExporter = function (mainLogger, gmeConfig) {
        // Call base class' constructor.
        AddOnBase.call(this, mainLogger, gmeConfig);
    };

    // Prototypal inheritance from AddOnBase.
    JSONLDExporter.prototype = Object.create(AddOnBase.prototype);
    JSONLDExporter.prototype.constructor = JSONLDExporter;

    /**
     * Gets the name of the JSONLDExporter.
     * @returns {string} The name of the AddOn.
     * @public
     */
    JSONLDExporter.prototype.getName = function () {
        return 'JSON-LD Exporter';
    };

    /**
     * Gets the semantic version (semver.org) of the JSONLDExporter.
     * @returns {string} The version of the AddOn.
     * @public
     */
    JSONLDExporter.prototype.getVersion = function () {
        return '0.1.0';
    };

    /**
     * This is invoked each time changes in the branch of the project are done. AddOns are allowed to make changes on
     * an update, but should not persist by themselves. (The AddOnManager will persist after each addOn has had its way
     * ordered by the usedAddOn registry in the rootNode).
     * Before each invocation a new updateResult is created which should be returned in the callback. There is no need
     * for the AddOn to report if it made changes or not, the monitor/manager will always persist and if there are no
     * changed objects - it won't commit to the storage.
     * @param {object} rootNode
     * @param {object} commitObj
     * @param {function(Error, AddOnUpdateResult)} callback
     */
    JSONLDExporter.prototype.update = function (rootNode, commitObj, callback) {
        var newName = commitObj.updater.toString();
        this.logger.info('JSONLDExporter in update at commitHash', commitObj._id);

        if (this.core.getAttribute(rootNode, 'name') !== newName) {
            this.logger.info('JSONLDExporter changing name of root to committer(s): ', newName);
            this.core.setAttribute(rootNode, 'name', newName);
            this.addCommitMessage('Changed rootNode name to "' + newName + '"');
        }

        callback(null, this.updateResult);
    };

    /**
     * Called once when the addOn is started for the first time.
     * @param {object} rootNode
     * @param {object} commitObj
     * @param {function(Error, AddOnUpdateResult} callback
     */
    JSONLDExporter.prototype.initialize = function (rootNode, commitObj, callback) {
        this.logger.info('JSONLDExporter got initialized at commitHash', commitObj._id);

        this.update(rootNode, commitObj, callback);
    };

    return JSONLDExporter;
});