/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 1.7.0 from webgme on Mon Jun 27 2016 16:44:40 GMT-0500 (CDT).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'plugin/PluginMessage',
    'common/util/ejs',
    'text!./Templates/language.4ml.ejs',
    'text!./Templates/node.4ml.ejs',
    'text!./Templates/project.4ml.ejs',
    './utils'
], function (PluginConfig,
             pluginMetadata,
             PluginBase,
             PluginMessage,
             ejs,
             languageTemplate,
             nodeTemplate,
             projectTemplate,
             utils) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of GenFORMULA.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin GenFORMULA.
     * @constructor
     */
    var GenFORMULA = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    };

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructue etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    GenFORMULA.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    GenFORMULA.prototype = Object.create(PluginBase.prototype);
    GenFORMULA.prototype.constructor = GenFORMULA;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    GenFORMULA.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            languageNodes = self.core.getAllMetaNodes(self.rootNode),
            i, node,
            languageParameters = {
                // pathToName: {},
                nodes: {}
            },
            languageText,
            nodeTexts = [];

        for (i in languageNodes) {
            node = languageNodes[i];
            languageParameters.nodes[i] = {
                id: self.core.getPath(node),
                // guid: self.core.getGuid(node),
                base: self.core.getPath(self.core.getBase(node)),
                // type: self.core.getPath(self.core.getBaseType(node)),
                name: self.core.getAttribute(node, 'name'),
                parent: self.core.getPath(self.core.getParent(node)),
                // isAbstract: self.core.isAbstract(node),
                // isMetaType: self.core.getBaseType(node) === node,
                isConnection: self.core.isConnection(node),
                meta: self.core.getJsonMeta(node),
                pointerNames: self.core.getValidPointerNames(node).sort(),
                attributeNames: self.core.getValidAttributeNames(node).sort()
            };

            // languageParameters.pathToName[i] = self.core.getAttribute(node, 'name');
        }

        languageText = ejs.render(languageTemplate, languageParameters);

        self.core.traverse(self.rootNode, {excludeRoot: true}, function (visited, next) {
            // This is the visit function
            //TODO check how to remove meta elements from the model
            /*if(self.core.isMetaNode(visited)){
                next(null);
                return;
            }*/
            var nodeParameters = {
                    id: self.core.getPath(visited),
                    base: self.core.getBase(visited) === null ? 'NULL' :
                        self.core.getPath(self.core.getBase(visited)),
                    parent: self.core.getParent(visited) === null ? 'NULL' :
                        self.core.getPath(self.core.getParent(visited)),
                    type: {
                        name: self.core.getAttribute(self.core.getBaseType(visited), 'name'),
                        id: self.core.getPath(self.core.getBaseType(visited))
                    },
                    name: self.core.getAttribute(visited, 'name'),
                    pointerNames: self.core.getValidPointerNames(visited).sort(),
                    attributeNames: self.core.getValidAttributeNames(visited).sort(),
                    isConnection: self.core.isConnection(visited),
                    attributes: {},
                    pointers: {}
                },
                i;

            for (i = 0; i < nodeParameters.attributeNames.length; i += 1) {
                nodeParameters.attributes[nodeParameters.attributeNames[i]] = {
                    type: self.core.getAttributeMeta(visited, nodeParameters.attributeNames[i]).type || 'string',
                    value: self.core.getAttribute(visited, nodeParameters.attributeNames[i])
                };
            }

            for (i = 0; i < nodeParameters.pointerNames.length; i += 1) {
                nodeParameters.pointers[nodeParameters.pointerNames[i]] =
                    self.core.getPointerPath(visited, nodeParameters.pointerNames[i]);
            }

            nodeTexts.push(ejs.render(nodeTemplate, nodeParameters));
            next(null);
        })
            .then(function () {
                var projectParameters = {
                        commitHash: self.commitHash,
                        projectName: self.projectName,
                        language: languageText,
                        nodes: nodeTexts,
                        constraints: self.core.getAttribute(self.rootNode, '_formulaConstraints') || ""
                    },
                    projectText = ejs.render(projectTemplate, projectParameters);

                // The first message contains the formula project
                self.result.addMessage(new PluginMessage({
                    commitHash: self.commitHash,
                    activeNode: '', //always point to the root
                    message: projectText
                }));

                // The second message contains the list of the names of the user defined constraints
                self.result.addMessage(new PluginMessage({
                    commitHash: self.commitHash,
                    activeNode: '', //always point to the root
                    message: JSON.stringify(utils.getUserConstraintNames(projectParameters.constraints))
                }));

                self.result.setSuccess(true);
                callback(null, self.result);
            })
            .catch(function (err) {
                self.logger.error(err);
                self.result.setSuccess(false);
                callback(null, self.result);
            })

    };

    return GenFORMULA;
});